routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('download/{product_slug}','Admin\DownloadsController@download')->name('public.download');

Route::prefix('admin')->middleware(['auth', 'acl', 'redirect.status'])->group( function () {
    Route::namespace('Admin')->group( function() {

        /** Dashboard */
        Route::get('/', 'DashboardController@index')->name('admin.dashboard');

        /** Pedidos */
        Route::resource('orders', 'OrdersController');

        /** ROTAS ADMINISTRATIVAS PROTEGIDAS */
        Route::group(['is' => 'admin'], function () {
            /** Rotas Categorias de Produtos */
            Route::resource('product-categories', 'ProductCategoriesController');

            /** Rotas Produtos */
            Route::resource('products', 'ProductsController');
            Route::post('products/{product}/change-status', 'ToggleProductsStatusController@toggle')->name('products.toggle-status');
            Route::get('products/{slug}/download', 'DownloadsController@download')->name('products.download');

            /** Rotas Usuários */
            Route::resource('users', 'UsersController');
            Route::post('users/{user}/change-status', 'ToggleUsersStatusController@toggle')->name('users.toggle-status');

        });
    });
});

app/Models/User.php
<?php

namespace Venus\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Kodeine\Acl\Traits\HasRole;

class User extends Authenticatable
{
    use Notifiable, HasRole;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'status', 'username', 'first_name', 'last_name', 'email', 'password',
        'cpf', 'cnpj', 'phone', 'address', 'cep', 'city', 'region', 'bank_account', 'websites'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace Venus\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Venus\Models\User;
use Kodeine\Acl\Models\Eloquent\Role;
use Venus\Http\Controllers\Controller;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::where('id', "!=", Auth::user()->id)->get();
        return view('admin.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::all();
        return view('admin.users.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $inputs = $request->all();
        $inputs['password'] = bcrypt($inputs['password']);

        try {
            $user = User::create($inputs);
            $user->assignRole($inputs['category']);
            return redirect()->route('users.index')->with(['success' => 'Usuário adicionado com sucesso']);
        } catch (\Exception $e) {
            return redirect()->route('users.index')->with(['error' => 'Ocorreu um erro no processo. Tente novamente em alguns instantes']);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user  = User::findOrFail($id);
        $roles = Role::all();
        return view('admin.users.edit', compact('roles', 'user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::findOrFail($id);
        $inputs = $request->all();

        if ($inputs['password'] != null)
        {
            $inputs['password'] = bcrypt($inputs['password']);
        } else {
            $inputs['password'] = $user->password;
        }

        $user->fill($inputs);

        if( $user->save() )
        {
            $user->revokeAllRoles();
            $user->assignRole($inputs['category']);
            return redirect()->route('users.index')->with(['success' => 'Usuário adicionado com sucesso']);
        } else {
            return redirect()->route('users.index')->with(['error' => 'Ocorreu um erro no processo. Tente novamente em alguns instantes']);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);
        $user->revokeAllRoles();
        if ($user->delete() )
        {
            return redirect()->route('users.index')->with(['success' => 'Usuário deletado com sucesso']);
        } else {
            return redirect()->route('users.index')->with(['error' => 'Ocorreu um erro no processamento. Tente novamente mais tarde.']);
        }
    }
}

resources/views/admin/users/create.blade.php
@extends('layouts.base')

@section('content')
    <div class="row">
        <div class="col-md-12 col-lg-12">
            <div class="box">
                <div class="box-header">
                    <h4 class="box-title">Formulário de cadastro</h4>
                </div>
                <div class="box-body">
                    <form enctype="multipart/form-data" action="{{ route('users.store') }}" method="post">
                        {{ csrf_field() }}
                        <div class="row">
                            <div class="col-sm-12 col-md-3 col-lg-3">
                                <div class="form-group">
                                    <label for="username">Nome</label>
                                    <input type="text" name="username" placeholder="Nome do Usuário" class="form-control" id="username" required>
                                </div>
                            </div>
                            <div class="col-sm-12 col-md-3 col-lg-3">
                                <div class="form-group">
                                    <label for="email">Email</label>
                                    <input type="email" name="email" placeholder="usuario@email.com" class="form-control" id="email" required>
                                </div>
                            </div>
                            <div class="col-sm-12 col-md-3 col-lg-3">
                                <div class="form-group">
                                    <label for="category">Categoria</label>
                                    <select name="category" class="form-control" id="user_category" required>
                                        @foreach( $roles as $role )
                                            <option value="{{ $role->slug }}">{{ $role->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="col-sm-12 col-md-3 col-lg-3">
                                <div class="form-group">
                                    <label for="password">Senha</label>
                                    <input type="password" name="password" placeholder="Senha" class="form-control" id="password" required>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-12 col-md-12 col-lg-12">
                                <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                                    <div class="panel panel-default">
                                        <div class="panel-heading" role="tab" id="headingOne">
                                            <h4 class="panel-title">
                                                <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                                    Informações de Revendedor
                                                </a>
                                            </h4>
                                        </div>
                                        <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                                            <div class="panel-body">
                                                <div class="row">
                                                    <div class="col-sm-12 col-md-7 col-lg-7">
                                                        <div class="form-group">
                                                            <label for="address">Endereço</label>
                                                            <input type="text" name="address" placeholder="Endereço" class="form-control" id="address">
                                                        </div>
                                                    </div>
                                                    <div class="col-sm-12 col-md-2 col-lg-2">
                                                        <div class="form-group">
                                                            <label for="cep">Cep</label>
                                                            <input type="text" name="cep" placeholder="00000-000" class="form-control" id="cep">
                                                        </div>
                                                    </div>
                                                    <div class="col-sm-12 col-md-2 col-lg-2">
                                                        <div class="form-group">
                                                            <label for="city">Cidade</label>
                                                            <input type="text" name="city" placeholder="Cidade" class="form-control" id="city">
                                                        </div>
                                                    </div>
                                                    <div class="col-sm-12 col-md-1 col-lg-1">
                                                        <div class="form-group">
                                                            <label for="region">Estado</label>
                                                            <input type="text" name="region" placeholder="XX" class="form-control" id="region">
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-sm-12 col-md-4 col-lg-4">
                                                        <div class="form-group">
                                                            <label for="cpf">Cpf</label>
                                                            <input type="text" name="cpf" placeholder="00000-000" class="form-control" id="cpf"
                                                                   data-mask="000.000.000-00" data-mask-reverse="true">
                                                        </div>
                                                    </div>
                                                    <div class="col-sm-12 col-md-4 col-lg-4">
                                                        <div class="form-group">
                                                            <label for="cnpj">Cnpj</label>
                                                            <input type="text" name="cnpj" placeholder="00000-000" class="form-control" id="cnpj"
                                                                   data-mask="00.000.000/0000-00" data-mask-reverse="true">
                                                        </div>
                                                    </div>
                                                    <div class="col-sm-12 col-md-4 col-lg-4">
                                                        <div class="form-group">
                                                            <label for="bank_account">Conta bancária</label>
                                                            <input type="text" name="bank_account" placeholder="BB 0000-0 00000-0" class="form-control" id="bank_account">
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-sm-12 col-md-9 col-lg-9">
                                                        <div class="form-group">
                                                            <label for="websites">Websites</label>
                                                            <input type="text" name="websites"
                                                                   placeholder="meusite.com.br;meuoutrosite.com.br;meuoutrooutrosite.com.br"
                                                                   class="form-control"
                                                                   id="websites">
                                                        </div>
                                                    </div>
                                                    <div class="col-sm-12 col-md-3 col-lg-3">
                                                        <div class="form-group">
                                                            <label for="phone">Celular/Whatsapp</label>
                                                            <input type="text" name="phone" placeholder="(xx)xxxxx-xxxx" class="form-control" id="phone"
                                                                   data-mask="(00)00000-0000">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="form-group text-right">
                            <button type="button" class="btn btn-danger" onclick="location.href='{{ route('users.index') }}';">
                                <i class="fa fa fa-fw fa-arrow-left"></i>Retornar</button>
                            <button type="submit" class="btn btn-primary">Adicionar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/admin/users/edit.blade.php
@extends('layouts.base')

@section('content')
    <div class="row">
        <div class="col-md-12 col-lg-12">
            <div class="box">
                <div class="box-header">
                    <h4 class="box-title">Formulário de edição</h4>
                </div>
                <div class="box-body">
                    <form enctype="multipart/form-data" action="{{ route('users.update', ['id' => $user->id]) }}" method="post">
                        {{ csrf_field() }}
                        {{ method_field('PUT') }}
                        <div class="row">
                            <div class="col-sm-12 col-md-3 col-lg-3">
                                <div class="form-group">
                                    <label for="username">Nome</label>
                                    <input type="text" name="username" placeholder="Nome do Usuário" class="form-control" id="username" value="{{ $user->username }}">
                                </div>
                            </div>
                            <div class="col-sm-12 col-md-3 col-lg-3">
                                <div class="form-group">
                                    <label for="email">Email</label>
                                    <input type="email" name="email" placeholder="usuario@email.com" class="form-control" id="email" value="{{ $user->email }}">
                                </div>
                            </div>
                            <div class="col-sm-12 col-md-3 col-lg-3">
                                <div class="form-group">
                                    <label for="category">Categoria</label>
                                    <select name="category" class="form-control" id="user_category">
                                        @foreach( $roles as $role )
                                            <option value="{{ $role->slug }}" @if( in_array($role->slug, $user->getRoles())) selected @endif>{{ $role->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="col-sm-12 col-md-3 col-lg-3">
                                <div class="form-group">
                                    <label for="password">Senha</label>
                                    <input type="password" name="password" placeholder="Senha" class="form-control" id="password">
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-12 col-md-12 col-lg-12">
                                <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                                    <div class="panel panel-default">
                                        <div class="panel-heading" role="tab" id="headingOne">
                                            <h4 class="panel-title">
                                                <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                                    Informações de Revendedor
                                                </a>
                                            </h4>
                                        </div>
                                        <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                                            <div class="panel-body">
                                                <div class="row">
                                                    <div class="col-sm-12 col-md-7 col-lg-7">
                                                        <div class="form-group">
                                                            <label for="address">Endereço</label>
                                                            <input type="text" name="address" placeholder="Endereço" class="form-control" id="address" value="{{ $user->address }}">
                                                        </div>
                                                    </div>
                                                    <div class="col-sm-12 col-md-2 col-lg-2">
                                                        <div class="form-group">
                                                            <label for="cep">Cep</label>
                                                            <input type="text" name="cep" placeholder="00000-000" class="form-control" id="cep" value="{{ $user->cep }}">
                                                        </div>
                                                    </div>
                                                    <div class="col-sm-12 col-md-2 col-lg-2">
                                                        <div class="form-group">
                                                            <label for="city">Cidade</label>
                                                            <input type="text" name="city" placeholder="Cidade" class="form-control" id="city" value="{{ $user->city }}">
                                                        </div>
                                                    </div>
                                                    <div class="col-sm-12 col-md-1 col-lg-1">
                                                        <div class="form-group">
                                                            <label for="region">Estado</label>
                                                            <input type="text" name="region" placeholder="XX" class="form-control" id="region" value="{{ $user->region }}">
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-sm-12 col-md-4 col-lg-4">
                                                        <div class="form-group">
                                                            <label for="cpf">Cpf</label>
                                                            <input type="text" name="cpf" placeholder="00000-000" class="form-control" id="cpf"
                                                                   data-mask="000.000.000-00" data-mask-reverse="true" value="{{ $user->cpf }}">
                                                        </div>
                                                    </div>
                                                    <div class="col-sm-12 col-md-4 col-lg-4">
                                                        <div class="form-group">
                                                            <label for="cnpj">Cnpj</label>
                                                            <input type="text" name="cnpj" placeholder="00000-000" class="form-control" id="cnpj"
                                                                   data-mask="00.000.000/0000-00" data-mask-reverse="true" value="{{ $user->cnpj }}">
                                                        </div>
                                                    </div>
                                                    <div class="col-sm-12 col-md-4 col-lg-4">
                                                        <div class="form-group">
                                                            <label for="bank_account">Conta bancária</label>
                                                            <input type="text" name="bank_account" placeholder="BB 0000-0 00000-0" class="form-control" id="bank_account" value="{{ $user->bank_account }}">
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-sm-12 col-md-9 col-lg-9">
                                                        <div class="form-group">
                                                            <label for="websites">Websites</label>
                                                            <input type="text" name="websites"
                                                                   placeholder="meusite.com.br;meuoutrosite.com.br;meuoutrooutrosite.com.br"
                                                                   class="form-control"
                                                                   id="websites" value="{{ $user->websites }}">
                                                        </div>
                                                    </div>
                                                    <div class="col-sm-12 col-md-3 col-lg-3">
                                                        <div class="form-group">
                                                            <label for="phone">Celular/Whatsapp</label>
                                                            <input type="text" name="phone" placeholder="(xx)xxxxx-xxxx" class="form-control" id="phone"
                                                                   data-mask="(00)00000-0000"
                                                                   value="{{ $user->phone }}">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="form-group text-right">
                            <button type="button" class="btn btn-danger" onclick="location.href='{{ route('users.index') }}';">
                                <i class="fa fa fa-fw fa-arrow-left"></i>Retornar</button>
                            <button type="submit" class="btn btn-primary">Atualizar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/admin/users/index.blade.php
@extends('layouts.base')

@section('content')
    <div class="row">
        <div class="col-md-12 col-lg-12">
            <div class="box with-border">
                <div class="box-header">
                    <h3 class="box-title">
                        Listagem geral dos Usuários do Sistema
                        <a role="button" class="btn btn-xs btn-primary" href="{{ route('users.create') }}">
                            <i class="fa fa-fw fa-plus"></i>
                            Adicionar
                        </a>
                    </h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                        </button>
                    </div>
                </div>
                <div class="box-body">
                    <table class="table table-hover table-condensed">
                        <thead>
                        <tr>
                            <th>Status</th>
                            <th>Nome</th>
                            <th>Email</th>
                            <th>Tipo</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($users as $user)
                            <tr>
                                <td>
                                    @if( $user->status )
                                        <span class="label label-success">
                                            <i class="fa fa-fw fa-check-circle-o"></i> ativo
                                        </span>
                                    @else
                                        <span class="label label-danger">
                                            <i class="fa fa-fw fa-close"></i> inativo
                                        </span>
                                    @endif
                                </td>
                                <td>{{ $user->username }}</td>
                                <td>{{ $user->email }}</td>
                                <td>
                                    @foreach( $user->getRoles() as $role )
                                        {{ $role }}
                                    @endforeach
                                </td>
                                <td class="text-right">

                                    @if( $user->status )
                                        <button type="btn" class="btn btn-danger btn-xs"
                                                onclick="user_toggle_status({{$user->id}})">desativar</button>
                                    @else
                                        <button type="btn" class="btn btn-success btn-xs"
                                                onclick="user_toggle_status({{$user->id}})">Ativar
                                        </button>
                                    @endif

                                    <div class="btn-group btn-group-xs" role="group" aria-label="...">
                                        <a role="button" class="btn btn-warning" href="{{ route('users.edit', ['id' => $user->id]) }}">
                                            <i class="fa fa-fw fa-edit"></i> atualizar
                                        </a>
                                        <button type="button" class="btn btn-danger"
                                            onclick="user_delete({{$user->id}})">
                                            <i class="fa fa-fw fa-trash-o"></i> deletar
                                        </button>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <!-- Formulário de exclusão geral -->
    <form id="user_delete_form" method="POST">
        {{ csrf_field() }}
        {{ method_field("DELETE") }}
    </form>
@stop

@section('js')
    <script>
        $('table').DataTable();
    </script>
@stop