routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('download/{product_slug}','Admin\DownloadsController@download')->name('public.download');

Route::prefix('admin')->middleware(['auth', 'acl', 'redirect.status'])->group( function () {
    Route::namespace('Admin')->group( function() {

        /** Dashboard */
        Route::get('/', 'DashboardController@index')->name('admin.dashboard');

        /** Pedidos */
        Route::resource('orders', 'OrdersController');

        /** ROTAS ADMINISTRATIVAS PROTEGIDAS */
        Route::group(['is' => 'admin'], function () {
            /** Rotas Categorias de Produtos */
            Route::resource('product-categories', 'ProductCategoriesController');

            /** Rotas Produtos */
            Route::resource('products', 'ProductsController');
            Route::post('products/{product}/change-status', 'ToggleProductsStatusController@toggle')->name('products.toggle-status');
            Route::get('products/{slug}/download', 'DownloadsController@download')->name('products.download');

            /** Rotas Usuários */
            Route::resource('users', 'UsersController');
            Route::post('users/{user}/change-status', 'ToggleUsersStatusController@toggle')->name('users.toggle-status');

        });
    });
});

app/Models/Order.php
<?php

namespace Venus\Models;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $fillable = ['user_id', 'customer', 'email'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function ebooks()
    {
        return $this->hasMany(OrderedProduct::class);
    }
}

app/Http/Controllers/Admin/OrdersController.php
<?php

namespace Venus\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

use Venus\Http\Controllers\Controller;
use Venus\Models\Order;
use Venus\Models\OrderedProduct;
use Venus\Models\Product;

class OrdersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //$products = Product::where('status', 1)->get();
        $orders   = null;

        if ( in_array('admin', Auth::user()->getRoles()) )
        {
            $orders = Order::all();
        } else {
            $orders = Order::where('user_id', Auth::user()->id);
        }

        return view('admin.orders.index', compact('orders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $products = Product::where('status', 1)->get();
        return view('admin.orders.create', compact('products'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $order = Order::create( $request->input() );
        $ids = $request->input('ebooks');

        foreach( $ids as $id )
        {
            $op = new OrderedProduct();
            $op->order_id = $order->id;
            $op->product_id = $id;
            $op->save();
        }

        /** Enviar email aqui */

        return redirect()->route('admin.oders.index')->with(['success' => 'Pedido realizado com sucesso']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/orders/create.blade.php
@extends('layouts.base')

@section('content')
    <div class="row">
        <div class="col-md-12 col-lg-12">
            <div class="box">
                <div class="box-header">
                    <h4 class="box-title">Formulário de cadastro</h4>
                </div>
                <div class="box-body">
                    <form enctype="multipart/form-data" action="{{ route('orders.store') }}" method="post">
                        {{ csrf_field() }}
                        <input type="hidden" name="user_id" value="{{ Auth::user()->id }}">
                        <div class="row">
                            <div class="col-sm-12 col-md-8 col-lg-8">
                                <div class="form-group">
                                    <label for="customer">Nome do Cliente</label>
                                    <input type="text" name="customer" placeholder="Nome do cliente" class="form-control" id="customer" required>
                                </div>
                            </div>
                            <div class="col-sm-12 col-md-4 col-lg-4">
                                <div class="form-group">
                                    <label for="email">Email para envio</label>
                                    <input type="text" name="email" placeholder="Email para envio" class="form-control" id="email" required>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-12 col-md-12 col-lg-12">
                                <div class="form-group">
                                    <label>Ebooks</label>
                                    <select name="ebooks[]" class="form-control" id="ebooks" multiple required>
                                        @foreach( $products as $ebook )
                                            <option value="{{ $ebook->id }}">{{ $ebook->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="form-group text-right">
                            <button type="button" class="btn btn-danger" onclick="location.href='{{ route('product-categories.index') }}';">
                                <i class="fa fa fa-fw fa-arrow-left"></i>Retornar</button>
                            <button type="submit" class="btn btn-primary">Adicionar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop

@section('js')
    <!-- Include ckEditor library -->
    <script src="https://cdn.ckeditor.com/ckeditor5/1.0.0-alpha.2/classic/ckeditor.js"></script>
    <!-- Initialize Quill editor -->
    <script>
        $(document).ready(function () {
            ClassicEditor
                .create( document.querySelector( 'textarea' ) )
                .catch( error => {
                console.error( error );
        });
            $('#ebooks').select2();
        });
    </script>
@stop

resources/views/admin/orders/index.blade.php
@extends('layouts.base')

@section('content')
    <div class="row">
        <div class="col-md-12 col-lg-12">
            <div class="box with-border">
                <div class="box-header">
                    <h3 class="box-title">
                        Listagem geral de Pedidos
                        <a role="button" class="btn btn-xs btn-primary" href="{{ route('orders.create') }}">
                            <i class="fa fa-fw fa-plus"></i>
                            Novo
                        </a>
                    </h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                        </button>
                    </div>
                </div>
                <div class="box-body">
                    <table class="table table-hover table-condensed">
                        <thead>
                        <tr>
                            <th>Status</th>
                            <th>Cliente</th>
                            <th>Email</th>
                            <th>Preço</th>
                            <th>Processamento</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($orders as $order)
                            <tr>
                                <td>
                                    @if( $order->status == 'enviado' )
                                        <span class="label label-success">
                                            <i class="fa fa-fw fa-check"></i> enviado
                                        </span>
                                    @elseif( $order->status == 'reenviado' )
                                        <span class="label label-warning">
                                            <i class="fa fa-fw fa-reorder"></i> renviado
                                        </span>
                                    @elseif( $order->status == 'reembolsado' )
                                        <span class="label label-danger">
                                            <i class="fa fa-fw fa-close"></i> reembolsado
                                        </span>
                                    @endif
                                </td>
                                <td>{{ $order->customer }}</td>
                                <td>{{ $order->email }}</td>
                                <td>R$ {{ number_format($order->total, 2, ',', '.') }}</td>
                                <td>{{ $order->created_at->format('d/m/Y H:i:s') }}</td>
                                <td class="text-right">
                                    @if( $order->status )
                                        <button type="btn" class="btn btn-danger btn-xs"
                                                onclick="order_toggle_status({{$order->id}})">desativar</button>
                                    @endif

                                    <div class="btn-group btn-group-xs" role="group" aria-label="...">
                                        <button type="button" class="btn btn-primary" id="order_{{ $order->id }}"
                                                onclick="order_view({{$order->id}}, 'order_{{$order->id}}')"
                                                data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i> Carregando...">
                                            <i class="fa fa-fw fa-eye"></i> exibir
                                        </button>
                                        <a role="button" class="btn btn-warning" href="{{ route('orders.edit', ['id' => $order->id]) }}">
                                            <i class="fa fa-fw fa-edit"></i> atualizar
                                        </a>
                                        <button type="button" class="btn btn-danger"
                                                onclick="order_delete({{$order->id}})">
                                            <i class="fa fa-fw fa-trash-o"></i> deletar
                                        </button>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>


    <div class="modal fade" id="modalOrderView" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header text-center">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

    <!-- Formulário de exclusão geral -->
    <form id="order_delete_form" method="POST">
        {{ csrf_field() }}
        {{ method_field("DELETE") }}
    </form>
@stop

@section('js')
    <script>
        $('table').DataTable();
    </script>
@stop