routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('download/{product_slug}','Admin\DownloadsController@download')->name('public.download');

Route::prefix('admin')->middleware(['auth', 'acl', 'redirect.status'])->group( function () {
    Route::namespace('Admin')->group( function() {

        /** Dashboard */
        Route::get('/', 'DashboardController@index')->name('admin.dashboard');

        /** Pedidos */
        Route::resource('orders', 'OrdersController');

        /** ROTAS ADMINISTRATIVAS PROTEGIDAS */
        Route::group(['is' => 'admin'], function () {
            /** Rotas Categorias de Produtos */
            Route::resource('product-categories', 'ProductCategoriesController');

            /** Rotas Produtos */
            Route::resource('products', 'ProductsController');
            Route::post('products/{product}/change-status', 'ToggleProductsStatusController@toggle')->name('products.toggle-status');
            Route::get('products/{slug}/download', 'DownloadsController@download')->name('products.download');

            /** Rotas Usuários */
            Route::resource('users', 'UsersController');
            Route::post('users/{user}/change-status', 'ToggleUsersStatusController@toggle')->name('users.toggle-status');

        });
    });
});

app/Models/Product.php
<?php

namespace Venus\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = [
        'code', 'name', 'slug', 'version', 'size', 'number_of_pages', 'price', 'description'
    ];

    /** Relationships */
    public function category()
    {
        return $this->belongsTo(ProductCategory::class, 'product_category_id');
    }

    public function ordereds()
    {
        return $this->hasMany(OrderedProduct::class);
    }
}

app/Http/Controllers/Admin/ProductsController.php
<?php

namespace Venus\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

use Venus\Http\Controllers\Controller;
use Venus\Http\Requests\Product\StoreProductRequest;
use Venus\Models\ProductCategory as Category;
use Venus\Models\Product;

class ProductsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::orderBy('id', 'DESC')->get();
        return view('admin.products.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all('id', 'name');
        return view('admin.products.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreProductRequest $request)
    {
        $inputs = $request->all();

        /**
         * Refatorar essa lógica.
         * Retirar ela daqui e pôr em um local mais acessível
         */
        /** trando valores monetários para o preco*/
        $str   = str_replace('.', '', $inputs['price']); // remove o ponto
        $valor = str_replace(',', '.', $str); // troca a vírgula por ponto
        $inputs['price'] = $valor;

        if ( $request->hasFile('file') && $request->file->isValid() )
        {
            $file_name = str_slug($request->input('name'),'-');
            $file_name .= '.pdf';
            $file = $request->file->storeAs('products', $file_name);

            $product = Product::create( $inputs );
            $product->file = $file;
            $product->product_category_id = $request->input('category');
            $product->save();
        }

        return redirect()->route('products.index')->with([
            'success' => 'Produto/Ebook adicionado com sucesso!'
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Product::findOrFail($id);
        $product->price = number_format($product->price, 2, ',', '.');
        $product->category = Category::find( $product->category->id);
        return response()->json($product);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categories = Category::all('id', 'name');
        $product = Product::findOrFail($id);
        return view('admin.products.edit', compact('product', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $product = Product::findOrFail($id);
        $inputs  = $request->except('file');

        /**
         * Refatorar essa lógica.
         * Retirar ela daqui e pôr em um local mais acessível
         */
        /** trando valores monetários para o preco */
        $str   = str_replace('.', '', $inputs['price']); // remove o ponto
        $valor = str_replace(',', '.', $str); // troca a vírgula por ponto
        $inputs['price'] = $valor;

        $product->fill($inputs);

        /**
         * Refatorar essa lógica.
         * Retirar ela daqui e pôr em um local mais acessível
         */
        /** Caso tenha haja um novo arquivo */
        if ($request->hasFile('file') && $request->file->isValid())
        {
            $file_name = explode('/', $product->file)[1];
            $file = $request->file->storeAs('products', $file_name);
            $product->file = $file;
        }

        try {
            $product->save();
            return redirect()->route('products.index')->with([
                'success' => 'Produto/Ebook atualizado'
            ]);
        } catch (\Exception $e) {
            return redirect()->route('products.index')->with([
                'error' => 'Ocorreu um erro no processo. Tente novamente em alguns instantes.'
            ]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::findOrFail($id);
        $file = $product->file;

        if ($product->delete() )
        {
            Storage::delete( $file );
            return redirect()->route('products.index')->with(['success' => 'Produto deletado com sucess']);
        } else {
            return redirect()->route('products')->with(['error' => 'Ocorreu um erro no processamento. Tente novamente mais tarde.']);
        }
    }
}

resources/views/admin/products/create.blade.php
@extends('layouts.base')

@section('breadcrumb')
    <ul class="breadcrumb">
        <li class="breadcrumb-item"><a href="">Administração</a></li>
        <li class="breadcrumb-item">Produtos</li>
        <li class="breadcrumb-item active">Adicionar</li>
    </ul>
@stop

@section('content')
    <div class="row">
        <div class="col-md-12 col-lg-12">
            <div class="box">
                <div class="box-header">
                    <h4 class="box-title">Formulário de cadastro</h4>
                </div>
                <div class="box-body">
                    <form enctype="multipart/form-data" action="{{ route('products.store') }}" method="post">
                        {{ csrf_field() }}
                        <div class="row">
                            <div class="col-sm-12 col-md-2 col-lg-2">
                                <div class="form-group">
                                    <label for="code">Código</label>
                                    <input type="text" name="code" placeholder="Código do produto" class="form-control" id="code" required>
                                </div>
                            </div>
                            <div class="col-sm-12 col-md-4 col-lg-4">
                                <div class="form-group">
                                    <label for="name">Título / Nome</label>
                                    <input type="text" name="name" placeholder="Título/Nome do produto" class="form-control" id="name" data-slugify="#slug" required>
                                </div>
                            </div>
                            <div class="col-sm-12 col-md-3 col-lg-3">
                                <div class="form-group">
                                    <label for="name">Slug</label>
                                    <input type="text" name="slug" class="form-control" id="slug" required>
                                </div>
                            </div>
                            <div class="col-sm-12 col-md-3 col-lg-3">
                                <div class="form-group">
                                    <label for="code">Categoria</label>
                                    <select name="category" class="form-control" id="product_category" required>
                                        @foreach( $categories as $category )
                                            <option value="{{ $category->id }}">{{ $category->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-12 col-md-3 col-lg-3">
                                <div class="form-group">
                                    <label for="version">Versão</label>
                                    <input type="text" name="version" placeholder="Versão do produto" class="form-control" id="version" required>
                                </div>
                            </div>
                            <div class="col-sm-12 col-md-3 col-lg-3">
                                <div class="form-group">
                                    <label for="size">Dimensões / Tamanho</label>
                                    <input type="size" name="size" placeholder="Dimensões e/ou tamanho do produto" class="form-control" id="size" required>
                                </div>
                            </div>
                            <div class="col-sm-12 col-md-3 col-lg-3">
                                <div class="form-group">
                                    <label for="number_of_pages">Quantidade de Páginas</label>
                                    <input type="number" min="0" name="number_of_pages" class="form-control" id="number_of_pages" required>
                                </div>
                            </div>
                            <div class="col-sm-12 col-md-3 col-lg-3">
                                <div class="form-group">
                                    <label for="price">Preço (R$)</label>
                                    <input type="text" name="price" placeholder="R$ 00,00" class="form-control" id="price"
                                           data-mask="#.##0,00" data-mask-reverse="true" required>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label>Descrição</label>
                            <textarea name="description" class="form-control"></textarea>
                        </div>

                        <div class="form-group">
                            <label for="file" >Arquivo / Ebook</label>
                            <input type="file" name="file" class="form-control-file" required>
                            <p class="help-block">Extensões permitidas: PDF</p>
                        </div>

                        <div class="form-group text-right">
                            <button type="button" class="btn btn-danger" onclick="location.href='{{ route('products.index') }}';">
                                <i class="fa fa fa-fw fa-arrow-left"></i>Retornar</button>
                            <button type="submit" class="btn btn-primary">Adicionar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop

@section('js')
    <!-- Include ckEditor library -->
    <script src="https://cdn.ckeditor.com/ckeditor5/1.0.0-alpha.2/classic/ckeditor.js"></script>
    <!-- Initialize Quill editor -->
    <script>
        $(document).ready(function () {
            ClassicEditor
                .create( document.querySelector( 'textarea' ) )
                .catch( error => {
                    console.error( error );
                });
            $('select').select2();
        });
    </script>
@stop

resources/views/admin/products/edit.blade.php
@extends('layouts.base')

@section('breadcrumb')
    <ul class="breadcrumb">
        <li class="breadcrumb-item"><a href="">Administração</a></li>
        <li class="breadcrumb-item">Produtos</li>
        <li class="breadcrumb-item active">Editar <i>{{ $product->name }}</i></li>
    </ul>
@stop

@section('content')
    <div class="row">
        <div class="col-md-12 col-lg-12">
            <div class="box">
                <div class="box-header">
                    <h4 class="box-title">Formulário de edição</h4>
                </div>
                <div class="box-body">
                    <form enctype="multipart/form-data" action="{{ route('products.update', ['id' => $product->id]) }}" method="post">
                        {{ csrf_field() }}
                        {{ method_field('PUT') }}
                        <div class="row">
                            <div class="col-sm-12 col-md-2 col-lg-2">
                                <div class="form-group">
                                    <label for="code">Código</label>
                                    <input type="text" name="code" placeholder="Código do produto" class="form-control" id="code" value="{{ $product->code }}">
                                </div>
                            </div>
                            <div class="col-sm-12 col-md-4 col-lg-4">
                                <div class="form-group">
                                    <label for="name">Título / Nome</label>
                                    <input type="text" name="name" placeholder="Título/Nome do produto" class="form-control" id="name" data-slugify="#slug" value="{{ $product->name }}">
                                </div>
                            </div>
                            <div class="col-sm-12 col-md-3 col-lg-3">
                                <div class="form-group">
                                    <label for="name">Slug</label>
                                    <input type="text" name="slug" class="form-control" id="slug" value="{{ $product->slug }}">
                                </div>
                            </div>
                            <div class="col-sm-12 col-md-3 col-lg-3">
                                <div class="form-group">
                                    <label for="code">Categoria</label>
                                    <select name="category" class="form-control" id="product_category">
                                        @foreach( $categories as $category )
                                            <option value="{{ $category->id }}" @if( $product->category->id == $category->id) selected @endif>{{ $category->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-12 col-md-3 col-lg-3">
                                <div class="form-group">
                                    <label for="version">Versão</label>
                                    <input type="text" name="version" placeholder="Versão do produto" class="form-control" id="version" value="{{ $product->version }}">
                                </div>
                            </div>
                            <div class="col-sm-12 col-md-3 col-lg-3">
                                <div class="form-group">
                                    <label for="size">Dimensões / Tamanho</label>
                                    <input type="size" name="size" placeholder="Dimensões e/ou tamanho do produto" class="form-control" id="size" value="{{ $product->size }}">
                                </div>
                            </div>
                            <div class="col-sm-12 col-md-3 col-lg-3">
                                <div class="form-group">
                                    <label for="number_of_pages">Quantidade de Páginas</label>
                                    <input type="number" min="0" name="number_of_pages" class="form-control" id="number_of_pages" value="{{ $product->number_of_pages }}">
                                </div>
                            </div>
                            <div class="col-sm-12 col-md-3 col-lg-3">
                                <div class="form-group">
                                    <label for="price">Preço (R$)</label>
                                    <input type="text" name="price" placeholder="R$ 00,00" class="form-control" id="price" value="{{ number_format($product->price, 2, ',', '.') }}"
                                           data-mask="#.##0,00" data-mask-reverse="true">
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label>Descrição</label>
                            <textarea name="description" class="form-control" rows="5">{{ $product->description }}</textarea>
                        </div>

                        <div class="form-group">
                            <label for="file" >Arquivo / Ebook</label>
                            <input type="file" name="file" class="form-control-file">
                            <p class="help-block">Extensões permitidas: PDF</p>
                        </div>

                        <div class="form-group text-right">
                            <button type="button" class="btn btn-danger" onclick="location.href='{{ route('products.index') }}';">
                                <i class="fa fa fa-fw fa-arrow-left"></i>Retornar</button>
                            <button type="submit" class="btn btn-primary">
                                <i class="fa fa-fw fa-check"></i>Atualizar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop

@section('js')
    <!-- Include ckEditor library -->
    <script src="https://cdn.ckeditor.com/ckeditor5/1.0.0-alpha.2/classic/ckeditor.js"></script>
    <!-- Initialize Quill editor -->
    <script>
        $(document).ready(function () {
            ClassicEditor
                .create( document.querySelector( 'textarea' ) )
                .catch( error => {
                console.error( error );
        });
            $('select').select2();
        });
    </script>
@stop

resources/views/admin/products/index.blade.php
@extends('layouts.base')

@section('content')
    <div class="row">
        <div class="col-md-12 col-lg-12">
            <div class="box with-border">
                <div class="box-header">
                    <h3 class="box-title">
                        Listagem geral dos Ebooks &nbsp;
                        <a role="button" class="btn btn-xs btn-primary" href="{{ route('products.create') }}">
                            <i class="fa fa-fw fa-plus"></i>
                            Adicionar
                        </a>
                        <a role="button" class="btn btn-xs btn-warning" href="{{ route('product-categories.create') }}">
                            <i class="fa fa-fw fa-plus"></i>
                            Adicionar Categoria
                        </a>
                    </h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                        </button>
                    </div>
                </div>
                <div class="box-body">
                    <table class="table table-hover table-condensed">
                        <thead>
                        <tr>
                            <th>Status</th>
                            <th>Código</th>
                            <th>Título</th>
                            <th>Versão</th>
                            <th>Categoria</th>
                            <th>Preço</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($products as $product)
                            <tr>
                                <td>
                                    @if( $product->status )
                                        <span class="label label-success">
                                            <i class="fa fa-fw fa-check-circle-o"></i> ativo
                                        </span>
                                    @else
                                        <span class="label label-danger">
                                            <i class="fa fa-fw fa-close"></i> inativo
                                        </span>
                                    @endif
                                </td>
                                <td>{{ $product->code }}</td>
                                <td>{{ $product->name }}</td>
                                <td>{{ $product->version }}</td>
                                <td>{{ $product->category->name }}</td>
                                <td>R$ {{ number_format($product->price, 2, ',', '.') }}</td>
                                <td class="text-right">
                                    @if(in_array('admin', Auth::user()->getRoles()) )
                                        <a role="button" class="btn btn-xs btn-default"
                                           href="{{ route('products.download', ['slug'=> $product->slug]) }}">
                                            <i class="fa fa-fw fa-download"></i> download
                                        </a>
                                    @endif

                                    @if( $product->status )
                                        <button type="btn" class="btn btn-danger btn-xs"
                                                onclick="product_toggle_status({{$product->id}})">desativar</button>
                                    @else
                                        <button type="btn" class="btn btn-success btn-xs"
                                                onclick="product_toggle_status({{$product->id}})">Ativar
                                        </button>
                                    @endif

                                    <div class="btn-group btn-group-xs" role="group" aria-label="...">
                                        <button type="button" class="btn btn-primary" id="product_{{ $product->id }}"
                                                onclick="product_view({{$product->id}}, 'product_{{$product->id}}')"
                                                data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i> Carregando...">
                                            <i class="fa fa-fw fa-eye"></i> exibir
                                        </button>
                                        <a role="button" class="btn btn-warning" href="{{ route('products.edit', ['id' => $product->id]) }}">
                                            <i class="fa fa-fw fa-edit"></i> atualizar
                                        </a>
                                        <button type="button" class="btn btn-danger"
                                            onclick="product_delete({{$product->id}})">
                                            <i class="fa fa-fw fa-trash-o"></i> deletar
                                        </button>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>


    <div class="modal fade" id="modalProductView" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header text-center">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

    <!-- Formulário de exclusão geral -->
    <form id="product_delete_form" method="POST">
        {{ csrf_field() }}
        {{ method_field("DELETE") }}
    </form>
@stop

@section('js')
    <script>
        $('table').DataTable();
    </script>
@stop