routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('download/{product_slug}','Admin\DownloadsController@download')->name('public.download');

Route::prefix('admin')->middleware(['auth', 'acl', 'redirect.status'])->group( function () {
    Route::namespace('Admin')->group( function() {

        /** Dashboard */
        Route::get('/', 'DashboardController@index')->name('admin.dashboard');

        /** Pedidos */
        Route::resource('orders', 'OrdersController');

        /** ROTAS ADMINISTRATIVAS PROTEGIDAS */
        Route::group(['is' => 'admin'], function () {
            /** Rotas Categorias de Produtos */
            Route::resource('product-categories', 'ProductCategoriesController');

            /** Rotas Produtos */
            Route::resource('products', 'ProductsController');
            Route::post('products/{product}/change-status', 'ToggleProductsStatusController@toggle')->name('products.toggle-status');
            Route::get('products/{slug}/download', 'DownloadsController@download')->name('products.download');

            /** Rotas Usuários */
            Route::resource('users', 'UsersController');
            Route::post('users/{user}/change-status', 'ToggleUsersStatusController@toggle')->name('users.toggle-status');

        });
    });
});

resources/views/admin/categories/create.blade.php
@extends('layouts.base')

@section('content')
    <div class="row">
        <div class="col-md-12 col-lg-12">
            <div class="box">
                <div class="box-header">
                    <h4 class="box-title">Formulário de cadastro</h4>
                </div>
                <div class="box-body">
                    <form enctype="multipart/form-data" action="{{ route('product-categories.store') }}" method="post">
                        {{ csrf_field() }}
                        <div class="row">
                            <div class="col-sm-12 col-md-12 col-lg-12">
                                <div class="form-group">
                                    <label for="name">Nome da categoria</label>
                                    <input type="text" name="name" placeholder="Nome da categoria" class="form-control" id="name" required>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-12 col-md-12 col-lg-12">
                                <div class="form-group">
                                    <label>Descrição</label>
                                    <textarea name="description" class="form-control"></textarea>
                                </div>
                            </div>
                        </div>
                        <div class="form-group text-right">
                            <button type="button" class="btn btn-danger" onclick="location.href='{{ route('product-categories.index') }}';">
                                <i class="fa fa fa-fw fa-arrow-left"></i>Retornar</button>
                            <button type="submit" class="btn btn-primary">Adicionar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop

@section('js')
    <!-- Include ckEditor library -->
    <script src="https://cdn.ckeditor.com/ckeditor5/1.0.0-alpha.2/classic/ckeditor.js"></script>
    <!-- Initialize Quill editor -->
    <script>
        $(document).ready(function () {
            ClassicEditor
                .create( document.querySelector( 'textarea' ) )
                .catch( error => {
                console.error( error );
            });
        });
    </script>
@stop

resources/views/admin/categories/edit.blade.php
@extends('layouts.base')

@section('content')
    <div class="row">
        <div class="col-md-12 col-lg-12">
            <div class="box">
                <div class="box-header">
                    <h4 class="box-title">Formulário de cadastro</h4>
                </div>
                <div class="box-body">
                    <form action="{{ route('product-categories.update', ['id' => $category->id]) }}" method="post">
                        {{ csrf_field() }}
                        {{ method_field('PUT') }}
                        <div class="row">
                            <div class="col-sm-12 col-md-12 col-lg-12">
                                <div class="form-group">
                                    <label for="name">Nome da categoria</label>
                                    <input type="text" name="name" placeholder="Nome da categoria" class="form-control" id="name" value="{{ $category->name }}">
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-12 col-md-12 col-lg-12">
                                <div class="form-group">
                                    <label>Descrição</label>
                                    <textarea name="description" class="form-control">{{ $category->description }}</textarea>
                                </div>
                            </div>
                        </div>
                        <div class="form-group text-right">
                            <button type="button" class="btn btn-danger" onclick="location.href='{{ route('product-categories.index') }}';">
                                <i class="fa fa fa-fw fa-arrow-left"></i>Retornar</button>
                            <button type="submit" class="btn btn-primary">Atualizar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop

@section('js')
    <!-- Include ckEditor library -->
    <script src="https://cdn.ckeditor.com/ckeditor5/1.0.0-alpha.2/classic/ckeditor.js"></script>
    <!-- Initialize Quill editor -->
    <script>
        $(document).ready(function () {
            ClassicEditor
                .create( document.querySelector( 'textarea' ) )
                .catch( error => {
                console.error( error );
        });
        });
    </script>
@stop

resources/views/admin/categories/index.blade.php
@extends('layouts.base')

@section('content')
    <div class="row">
        <div class="col-md-12 col-lg-12">
            <div class="box with-border">
                <div class="box-header">
                    <h3 class="box-title">
                        Listagem geral de Categorias &nbsp;
                        <a role="button" class="btn btn-xs btn-primary" href="{{ route('product-categories.create') }}">
                            <i class="fa fa-fw fa-plus"></i>
                            Adicionar Categoria
                        </a>
                    </h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                        </button>
                    </div>
                </div>
                <div class="box-body">
                    <table class="table table-hover table-condensed">
                        <thead>
                        <tr>
                            <th>Nome</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                            @foreach($categories as $category)
                            <tr>
                                <td>{{ $category->name }}</td>
                                <td class="text-right">
                                    <div class="btn-group btn-group-xs" role="group" aria-label="...">
                                        <a role="button" class="btn btn-warning" href="{{ route('product-categories.edit', ['id' => $category->id]) }}">
                                            <i class="fa fa-fw fa-edit"></i> atualizar
                                        </a>
                                        <button type="button" class="btn btn-danger"
                                                onclick="product_category_delete({{$category->id}})">
                                            <i class="fa fa-fw fa-trash-o"></i> deletar
                                        </button>
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <!-- Formulário de exclusão geral -->
    <form id="product_category_delete_form" method="POST">
        {{ csrf_field() }}
        {{ method_field("DELETE") }}
    </form>
@stop

@section('js')
    <script>
        $('table').DataTable();
    </script>
@stop